[package]
name = "meatered-API"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
warp = "0.3.6"
