[package]
name = "meatered-API"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = "0.7.3"
tokio = "1.36.0"
warp = "0.3.6"
